<a href="https://colab.research.google.com/github/mathuraryan036-collab/ML-GOOGLE-COLAB-/blob/main/3_1_Numpy_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Numerical Python

Advantages of Numpy Arrays:
1. Allows several Mathematical Operations
2. Faster Operations

In [ ]:
import numpy as np

List vs Numpy - Time Taken by each (Numpy is faster than lists)

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0009747729999993737


Time taken by Numpy array

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00017127200000022214


#Numpy Array

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# Creating a 1-D Array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
#Creating a 2-D Array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
# create a numpy arrays of Zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create numpy arrays of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an Identity Matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.13939213 0.63429471 0.3704995  0.23251791]
 [0.93225964 0.30941171 0.18901836 0.78861821]
 [0.83156851 0.97218419 0.75790587 0.40091445]]


In [ ]:
# randomm integer values array
c = np.random.randint(10,100,(3,5))
print(c)

[[78 40 46 82 93]
 [34 80 70 87 67]
 [30 69 33 54 66]]


In [ ]:
# array of evenly spaced values
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

#Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[68 69 89 12 49]
 [81 42 40 39 83]
 [82 20 13 17 81]
 [28 70 28 41 66]
 [33 38 21 21 89]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# checking the number of elements in the array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


#Mathematical Operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[8 8 6]
 [5 5 5]
 [3 1 2]]
[[14 14 18]
 [15 17 16]
 [14 16 14]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 22 24]
 [20 22 21]
 [17 17 16]]
[[ -6  -6 -12]
 [-10 -12 -11]
 [-11 -15 -12]]
[[112 112 108]
 [ 75  85  80]
 [ 42  16  28]]
[[0.57142857 0.57142857 0.33333333]
 [0.33333333 0.29411765 0.3125    ]
 [0.21428571 0.0625     0.14285714]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 22 24]
 [20 22 21]
 [17 17 16]]
[[ -6  -6 -12]
 [-10 -12 -11]
 [-11 -15 -12]]
[[112 112 108]
 [ 75  85  80]
 [ 42  16  28]]
[[0.57142857 0.57142857 0.33333333]
 [0.33333333 0.29411765 0.3125    ]
 [0.21428571 0.0625     0.14285714]]


#Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 2 2]
 [1 7 9]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 1]
 [2 7]
 [2 9]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 3 3]
 [2 4 7]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[2 2]
 [3 4]
 [3 7]]
(3, 2)


In [ ]:
# reshape an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 0 7]
 [4 3 2]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 0]
 [7 4]
 [3 2]]
(3, 2)
