In [ ]:
import numpy as np

Matrix Addition

In [ ]:
# creating two matrices
A = np.array([[2, 3], [4, 5]])
B = np.array([[6, 7], [8, 9]])

In [ ]:
print(A)

[[2 3]
 [4 5]]


In [ ]:
print(B)

[[6 7]
 [8 9]]


In [ ]:
A.shape
B.shape

(2, 2)

In [ ]:
sum = A + B
print(sum)

[[ 8 10]
 [12 14]]


In [ ]:
# creating two matrices with random values
matrix_1 = np.random.randint(10, size=(3, 3))
matrix_2 = np.random.randint(20, size=(3, 3))

In [ ]:
print(matrix_1)

[[2 6 6]
 [1 3 3]
 [8 7 3]]


In [ ]:
print(matrix_2)

[[19  5  3]
 [15  0  9]
 [12  2 15]]


In [ ]:
sum = matrix_1 + matrix_2
print(sum)

[[19  5  9]
 [18  3 15]
 [17  9 21]]


Matrix Subtraction

In [ ]:
# creating two matrices
A = np.array([[2, 3], [4, 5]])
B = np.array([[6, 7], [8, 9]])

In [ ]:
print(A)

[[2 3]
 [4 5]]


In [ ]:
print(B)

[[6 7]
 [8 9]]


In [ ]:
A.shape
B.shape

(2, 2)

In [ ]:
difference = A - B
print(difference)

[[-4 -4]
 [-4 -4]]


In [ ]:
# creating two matrices with random values
matrix_1 = np.random.randint(10, size=(3, 3))
matrix_2 = np.random.randint(20, size=(3, 3))

In [ ]:
print(matrix_1)

[[4 9 7]
 [3 0 5]
 [6 3 9]]


In [ ]:
print(matrix_2)

[[ 7 15 10]
 [ 2  9  7]
 [13 10 18]]


In [ ]:
difference = matrix_1 - matrix_2
print(difference)

[[-3 -6 -3]
 [ 1 -9 -2]
 [-7 -7 -9]]


Multiplying a matrix by a scalar

In [ ]:
x = 5
y = np.random.randint(10, size=(4, 4))
print(y)

[[1 4 5 7]
 [6 8 4 9]
 [4 0 6 6]
 [5 1 9 3]]


In [ ]:
product = np.multiply(x, y)
print(product)

[[ 5 20 25 35]
 [30 40 20 45]
 [20  0 30 30]
 [25  5 45 15]]


Multiplying Matrices

In [ ]:
# creating two matrices with random values
A = np.random.randint(5, size=(3, 3))
B = np.random.randint(5, size=(3, 3))

In [ ]:
print(A)

[[1 2 0]
 [4 2 4]
 [4 0 4]]


In [ ]:
print(B)

[[0 4 3]
 [4 4 1]
 [1 4 3]]


In [ ]:
product = np.dot(A, B)

In [ ]:
print(product)

[[ 8 12  5]
 [12 40 26]
 [ 4 32 24]]


In [ ]:
product.shape

(3, 3)

Element wise matrix multiplication

In [ ]:
# creating two matrices with random values
A = np.random.randint(5, size=(3, 3))
B = np.random.randint(5, size=(3, 3))

In [ ]:
print(A)

[[2 2 1]
 [3 4 4]
 [4 1 2]]


In [ ]:
print(B)

[[2 4 1]
 [1 0 1]
 [0 1 2]]


In [ ]:
product = np.multiply(A, B)
print(product)

[[4 8 1]
 [3 0 4]
 [0 1 4]]


In [ ]:
product.shape

(3, 3)