In [ ]:
import numpy as np

Creating a Matrix using Numpy

In [ ]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2 = np.array([[5,6,7],[6,7,9],[4,5,6]])
print(matrix_2)

[[5 6 7]
 [6 7 9]
 [4 5 6]]


In [ ]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [ ]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.71485813 0.55616996 0.55284445]
 [0.66222237 0.69297087 0.31631009]
 [0.0369953  0.99392806 0.82243088]]


In [ ]:
# creating matrix with random integer
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[96 52  7 12  8]
 [33 22 30 31  5]
 [25 40  4 16 52]
 [29 77 90 49 45]]


Matrix with all the values as 1

In [ ]:
matrix_3 = np.ones((3,4))
print(matrix_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
matrix_3 = np.ones((3,4), dtype=int)
print(matrix_3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Null Matrix

In [ ]:
null_matrix = np.zeros((3,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
null_matrix = np.zeros((3,4), dtype=int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Identity Matrix

In [ ]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
identity_matrix = np.eye((5), dtype = int)
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Transpose of a Matrix

In [ ]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[13 28  9 59 23]
 [18 37 39 92 69]
 [ 7  4 52 31 66]
 [ 1 30 72 43 79]]


In [ ]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[13 18  7  1]
 [28 37  4 30]
 [ 9 39 52 72]
 [59 92 31 43]
 [23 69 66 79]]
